# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  name: cloud-security-workshop
  description: "☘️ Cloud security workshop"
  topics: security, cloud, aws
  homepage: https://github.com/ik-workshop/cloud-security-workshop
  private: false
  has_projects: false
  has_wiki: false
  is_template: false
  has_downloads: false

branches:
  - name: main
